name: Build and Push Docker Image

on:
  push:
    branches: ["main"]
    tags:
      - "v*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSKEY }}

      - name: Determine Docker Image Tags
        id: docker_tags
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            echo "::set-output name=tags::bertoja/paw-patrol-tower:stable-main"
          elif [[ $GITHUB_REF == refs/tags/v* ]]; then
            echo "::set-output name=tags::bertoja/paw-patrol-tower:latest"
          fi
          
      - name: Build and push Docker image
        run: docker buildx build --platform linux/amd64,linux/arm64/v8 -t ${{ steps.docker_tags.outputs.tags }} --push .
        env:
          DOCKER_BUILDKIT: 1